export type BackendHttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type BackendApiDomain =
  | "activityFeed"
  | "agile"
  | "authentication"
  | "costEntries"
  | "health"
  | "navigation"
  | "notifications"
  | "projects"
  | "reports"
  | "search"
  | "sprints"
  | "timeEntries"
  | "users"
  | "wiki"
  | "workItems";

export type BackendPolicy =
  | "Public"
  | "Anonymous"
  | "CanRead"
  | "CanWrite"
  | "CanWriteProject"
  | "CanWriteSystem"
  | "ManageUsers";

export type FrontendTransport = "specialized" | "passthrough";

export type FrontendUiCoverage =
  "live-ui" | "adapter-only" | "ui-not-integrated" | "no-ui" | "infrastructure";

export interface BackendApiContract {
  backendPath: string;
  domain: BackendApiDomain;
  frontendPath: string;
  id: string;
  method: BackendHttpMethod;
  notes?: string;
  policy: BackendPolicy;
  request: string;
  response: string;
  transport: FrontendTransport;
  ui: FrontendUiCoverage;
}

type ContractTuple = readonly [
  id: string,
  domain: BackendApiDomain,
  method: BackendHttpMethod,
  frontendPath: string,
  backendPath: string,
  policy: BackendPolicy,
  request: string,
  response: string,
  transport: FrontendTransport,
  ui: FrontendUiCoverage,
  notes?: string,
];

const contractTuples = [
  [
    "activity-feed.list",
    "activityFeed",
    "GET",
    "/api/v1/activity-feed",
    "/activity-feed",
    "CanRead",
    "GetActivityFeedQuery",
    "PagedActivityFeedResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "agile.backlogs.list",
    "agile",
    "GET",
    "/api/v1/agile/backlogs",
    "/agile/backlogs",
    "CanRead",
    "GetBacklogQuery",
    "PagedAgileBacklogResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "agile.backlogs.reorder",
    "agile",
    "PATCH",
    "/api/v1/agile/backlogs/reorder",
    "/agile/backlogs/reorder",
    "CanWriteProject",
    "ReorderBacklogRequest",
    "ReorderBacklogResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "agile.boards.get",
    "agile",
    "GET",
    "/api/v1/agile/boards",
    "/agile/boards",
    "CanRead",
    "GetBoardQuery",
    "AgileBoardResponse",
    "passthrough",
    "ui-not-integrated",
    "The board screen currently renders static lanes.",
  ],
  [
    "agile.boards.active-sprint",
    "agile",
    "GET",
    "/api/v1/agile/sprints/active/board",
    "/agile/sprints/active/board",
    "CanRead",
    "GetActiveSprintBoardQuery",
    "AgileBoardResponse",
    "passthrough",
    "ui-not-integrated",
    "The board screen currently renders static lanes.",
  ],
  [
    "agile.sprints.burndown",
    "agile",
    "GET",
    "/api/v1/agile/sprints/{sprintId}/burndown",
    "/agile/sprints/{sprintId}/burndown",
    "CanRead",
    "GetSprintBurndownQuery",
    "SprintBurndownResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "agile.boards.move",
    "agile",
    "PATCH",
    "/api/v1/agile/boards/move",
    "/agile/boards/move",
    "CanWriteProject",
    "MoveBoardItemRequest",
    "MoveBoardItemResponse",
    "passthrough",
    "ui-not-integrated",
    "The board is read-only and static.",
  ],

  [
    "auth.login",
    "authentication",
    "POST",
    "/api/auth/login/web-app",
    "/auth/login/web-app",
    "Anonymous",
    "LoginByEmailRequest",
    "ApiResponse<bool> + cookies",
    "specialized",
    "live-ui",
  ],
  [
    "auth.register",
    "authentication",
    "POST",
    "/api/auth/register",
    "/auth/register",
    "CanWriteSystem",
    "RegisterUserRequest",
    "ApiResponse<bool>",
    "specialized",
    "adapter-only",
  ],
  [
    "auth.refresh",
    "authentication",
    "POST",
    "/api/auth/refresh",
    "/auth/refresh",
    "Anonymous",
    "Cookie pair",
    "ApiResponse<bool> + cookies",
    "specialized",
    "adapter-only",
  ],
  [
    "auth.logout",
    "authentication",
    "POST",
    "/api/auth/logout",
    "/auth/logout",
    "CanRead",
    "Cookie pair",
    "ApiResponse<bool> + cleared cookies",
    "specialized",
    "live-ui",
  ],
  [
    "auth.me",
    "authentication",
    "GET",
    "/api/auth/me",
    "/auth/me",
    "CanRead",
    "None",
    "ApiResponse<bool> (current TODO payload)",
    "specialized",
    "live-ui",
  ],
  [
    "auth.oidc.start",
    "authentication",
    "GET",
    "/api/auth/oidc/{provider}/start",
    "/auth/oidc/{provider}/start",
    "Anonymous",
    "Provider path",
    "302 redirect",
    "specialized",
    "live-ui",
  ],
  [
    "auth.oidc.callback",
    "authentication",
    "GET",
    "/api/auth/oidc/{provider}/callback",
    "/auth/oidc/{provider}/callback",
    "Anonymous",
    "state/code/error query",
    "302 redirect + cookies",
    "specialized",
    "live-ui",
  ],

  [
    "cost-entries.create",
    "costEntries",
    "POST",
    "/api/v1/cost-entries/work-packages/{workPackageId}",
    "/cost-entries/work-packages/{workPackageId}",
    "CanWrite",
    "CreateCostEntryRequest",
    "CostEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "cost-entries.update",
    "costEntries",
    "PATCH",
    "/api/v1/cost-entries/work-packages/{workPackageId}/{costEntryId}",
    "/cost-entries/work-packages/{workPackageId}/{costEntryId}",
    "CanWrite",
    "UpdateCostEntryRequest",
    "CostEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "cost-entries.delete",
    "costEntries",
    "DELETE",
    "/api/v1/cost-entries/work-packages/{workPackageId}/{costEntryId}",
    "/cost-entries/work-packages/{workPackageId}/{costEntryId}",
    "CanWrite",
    "Path IDs",
    "CostEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "cost-entries.by-work-item",
    "costEntries",
    "GET",
    "/api/v1/cost-entries/work-packages/{workPackageId}",
    "/cost-entries/work-packages/{workPackageId}",
    "CanRead",
    "GetCostEntriesQuery",
    "PagedCostEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "cost-entries.by-project",
    "costEntries",
    "GET",
    "/api/v1/cost-entries/projects/{projectId}",
    "/cost-entries/projects/{projectId}",
    "CanRead",
    "GetCostEntriesQuery",
    "PagedCostEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "cost-entries.by-actor",
    "costEntries",
    "GET",
    "/api/v1/cost-entries/actors/{actorUserId}",
    "/cost-entries/actors/{actorUserId}",
    "CanRead",
    "GetCostEntriesQuery",
    "PagedCostEntryResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "health.get",
    "health",
    "GET",
    "/api/v1/health",
    "/api/health",
    "Public",
    "None",
    "Empty 200",
    "passthrough",
    "infrastructure",
  ],
  [
    "navigation.get",
    "navigation",
    "GET",
    "/api/v1/navigation",
    "/navigation",
    "CanRead",
    "None",
    "NavigationResponse",
    "passthrough",
    "ui-not-integrated",
    "The app shell currently uses local navigation configuration.",
  ],

  [
    "notifications.list",
    "notifications",
    "GET",
    "/api/v1/notifications",
    "/notifications",
    "CanRead",
    "GetNotificationsQuery",
    "PagedNotificationResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "notifications.read",
    "notifications",
    "PATCH",
    "/api/v1/notifications/{notificationId}/read",
    "/notifications/{notificationId}/read",
    "CanRead",
    "Notification ID",
    "NotificationItemResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "notifications.read-all",
    "notifications",
    "PATCH",
    "/api/v1/notifications/read-all",
    "/notifications/read-all",
    "CanRead",
    "None",
    "MarkAllNotificationsReadResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "projects.list",
    "projects",
    "GET",
    "/api/v1/projects",
    "/projects",
    "CanWriteSystem",
    "GetProjectsQuery",
    "PagedProjectSummaryResponse",
    "specialized",
    "live-ui",
    "Backend currently limits the list to Admin through CanWriteSystem.",
  ],
  [
    "projects.detail",
    "projects",
    "GET",
    "/api/v1/projects/{projectId}",
    "/projects/{projectId}",
    "CanRead",
    "Project ID",
    "ProjectDetailResponse",
    "specialized",
    "live-ui",
  ],
  [
    "projects.documents.upload-url",
    "projects",
    "POST",
    "/api/v1/projects/{projectId}/documents/upload-url",
    "/projects/{projectId}/documents/upload-url",
    "CanWriteProject",
    "CreateProjectDocumentUploadUrlRequest",
    "ProjectDocumentUploadUrlResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.documents.create",
    "projects",
    "POST",
    "/api/v1/projects/{projectId}/documents",
    "/projects/{projectId}/documents",
    "CanWriteProject",
    "LinkProjectDocumentRequest",
    "ProjectDocumentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.documents.list",
    "projects",
    "GET",
    "/api/v1/projects/{projectId}/documents",
    "/projects/{projectId}/documents",
    "CanRead",
    "GetProjectDocumentsQuery",
    "PagedProjectDocumentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.documents.detail",
    "projects",
    "GET",
    "/api/v1/projects/{projectId}/documents/{documentId}",
    "/projects/{projectId}/documents/{documentId}",
    "CanRead",
    "Path IDs",
    "ProjectDocumentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.documents.delete",
    "projects",
    "DELETE",
    "/api/v1/projects/{projectId}/documents/{documentId}",
    "/projects/{projectId}/documents/{documentId}",
    "CanWriteProject",
    "Path IDs",
    "ProjectDocumentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.members.list",
    "projects",
    "GET",
    "/api/v1/projects/{projectId}/members",
    "/projects/{projectId}/members",
    "CanWriteProject",
    "GetProjectMembersQuery",
    "PagedMemberProjectionResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.members.add",
    "projects",
    "POST",
    "/api/v1/projects/{projectId}/members",
    "/projects/{projectId}/members",
    "CanWriteProject",
    "AddProjectMemberRequest",
    "ProjectMembershipResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.members.update",
    "projects",
    "PATCH",
    "/api/v1/projects/{projectId}/members/{userId}",
    "/projects/{projectId}/members/{userId}",
    "CanWriteProject",
    "UpdateProjectMemberRoleRequest",
    "ProjectMembershipResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "projects.members.remove",
    "projects",
    "DELETE",
    "/api/v1/projects/{projectId}/members/{userId}",
    "/projects/{projectId}/members/{userId}",
    "CanWriteProject",
    "Path IDs",
    "ProjectMembershipResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "reports.time-cost",
    "reports",
    "GET",
    "/api/v1/reports/projects/{projectId}/time-cost",
    "/reports/projects/{projectId}/time-cost",
    "CanRead",
    "GetTimeCostReportQuery",
    "TimeCostReportResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "search.get",
    "search",
    "GET",
    "/api/v1/search",
    "/search",
    "CanRead",
    "SearchQuery",
    "SearchResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "sprints.list",
    "sprints",
    "GET",
    "/api/v1/projects/{projectId}/sprints",
    "/projects/{projectId}/sprints",
    "CanRead",
    "GetSprintsQuery",
    "PagedSprintResponse",
    "specialized",
    "live-ui",
  ],
  [
    "sprints.create",
    "sprints",
    "POST",
    "/api/v1/projects/{projectId}/sprints",
    "/projects/{projectId}/sprints",
    "CanWriteProject",
    "CreateSprintRequest",
    "SprintResponse",
    "specialized",
    "live-ui",
  ],
  [
    "sprints.detail",
    "sprints",
    "GET",
    "/api/v1/projects/{projectId}/sprints/{sprintId}",
    "/projects/{projectId}/sprints/{sprintId}",
    "CanRead",
    "Path IDs",
    "SprintResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "sprints.update.put",
    "sprints",
    "PUT",
    "/api/v1/projects/{projectId}/sprints/{sprintId}",
    "/projects/{projectId}/sprints/{sprintId}",
    "CanWriteProject",
    "UpdateSprintRequest",
    "SprintResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "sprints.update.patch",
    "sprints",
    "PATCH",
    "/api/v1/projects/{projectId}/sprints/{sprintId}",
    "/projects/{projectId}/sprints/{sprintId}",
    "CanWriteProject",
    "UpdateSprintRequest",
    "SprintResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "sprints.delete",
    "sprints",
    "DELETE",
    "/api/v1/projects/{projectId}/sprints/{sprintId}",
    "/projects/{projectId}/sprints/{sprintId}",
    "CanWriteProject",
    "Path IDs",
    "SprintResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "time-entries.create",
    "timeEntries",
    "POST",
    "/api/v1/time-entries/work-packages/{workPackageId}",
    "/time-entries/work-packages/{workPackageId}",
    "CanWrite",
    "CreateTimeEntryRequest",
    "TimeEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "time-entries.update",
    "timeEntries",
    "PATCH",
    "/api/v1/time-entries/work-packages/{workPackageId}/{timeEntryId}",
    "/time-entries/work-packages/{workPackageId}/{timeEntryId}",
    "CanWrite",
    "UpdateTimeEntryRequest",
    "TimeEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "time-entries.delete",
    "timeEntries",
    "DELETE",
    "/api/v1/time-entries/work-packages/{workPackageId}/{timeEntryId}",
    "/time-entries/work-packages/{workPackageId}/{timeEntryId}",
    "CanWrite",
    "Path IDs",
    "TimeEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "time-entries.by-work-item",
    "timeEntries",
    "GET",
    "/api/v1/time-entries/work-packages/{workPackageId}",
    "/time-entries/work-packages/{workPackageId}",
    "CanRead",
    "GetTimeEntriesQuery",
    "PagedTimeEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "time-entries.by-project",
    "timeEntries",
    "GET",
    "/api/v1/time-entries/projects/{projectId}",
    "/time-entries/projects/{projectId}",
    "CanRead",
    "GetTimeEntriesQuery",
    "PagedTimeEntryResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "time-entries.by-actor",
    "timeEntries",
    "GET",
    "/api/v1/time-entries/actors/{actorUserId}",
    "/time-entries/actors/{actorUserId}",
    "CanRead",
    "GetTimeEntriesQuery",
    "PagedTimeEntryResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "users.list",
    "users",
    "GET",
    "/api/v1/users",
    "/users",
    "ManageUsers",
    "Pagination/filter query",
    "Paged user response",
    "specialized",
    "live-ui",
    "The assignee picker uses this Admin-only endpoint.",
  ],
  [
    "users.detail",
    "users",
    "GET",
    "/api/v1/users/{userId}",
    "/users/{userId}",
    "ManageUsers",
    "User ID",
    "UserDetailDTO",
    "passthrough",
    "no-ui",
  ],
  [
    "users.update",
    "users",
    "PUT",
    "/api/v1/users/{userId}",
    "/users/{userId}",
    "ManageUsers",
    "UpdateUserRequest",
    "UserDetailDTO",
    "passthrough",
    "no-ui",
  ],
  [
    "users.delete",
    "users",
    "DELETE",
    "/api/v1/users/{userId}",
    "/users/{userId}",
    "ManageUsers",
    "User ID",
    "UserDetailDTO",
    "passthrough",
    "no-ui",
  ],
  [
    "users.invite",
    "users",
    "POST",
    "/api/v1/users/invite",
    "/users/invite",
    "ManageUsers",
    "InviteUserRequest",
    "InviteUserResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "wiki.create",
    "wiki",
    "POST",
    "/api/v1/projects/{projectId}/wiki/pages",
    "/projects/{projectId}/wiki/pages",
    "CanWrite",
    "CreateWikiPageRequest",
    "WikiPageResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "wiki.list",
    "wiki",
    "GET",
    "/api/v1/projects/{projectId}/wiki/pages",
    "/projects/{projectId}/wiki/pages",
    "CanRead",
    "GetWikiPagesQuery",
    "PagedWikiPageResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "wiki.detail",
    "wiki",
    "GET",
    "/api/v1/projects/{projectId}/wiki/pages/{slug}",
    "/projects/{projectId}/wiki/pages/{slug}",
    "CanRead",
    "revision query",
    "WikiPageResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "wiki.update",
    "wiki",
    "PATCH",
    "/api/v1/projects/{projectId}/wiki/pages/{slug}",
    "/projects/{projectId}/wiki/pages/{slug}",
    "CanWrite",
    "UpdateWikiPageRequest",
    "WikiPageResponse",
    "passthrough",
    "no-ui",
  ],

  [
    "work-items.create",
    "workItems",
    "POST",
    "/api/v1/work-items",
    "/work-packages",
    "CanWrite",
    "CreateWorkPackageRequest",
    "WorkPackageResultResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.update.put",
    "workItems",
    "PUT",
    "/api/v1/work-items/{workItemId}",
    "/work-packages/{workItemId}",
    "CanWrite",
    "UpdateWorkPackageRequest",
    "WorkPackageResultResponse",
    "specialized",
    "adapter-only",
  ],
  [
    "work-items.update.patch",
    "workItems",
    "PATCH",
    "/api/v1/work-items/{workItemId}",
    "/work-packages/{workItemId}",
    "CanWrite",
    "UpdateWorkPackageRequest",
    "WorkPackageResultResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.delete",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}",
    "/work-packages/{workItemId}",
    "CanWriteProject",
    "Work item ID",
    "WorkPackageResultResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.list",
    "workItems",
    "GET",
    "/api/v1/work-items",
    "/work-packages",
    "CanRead",
    "GetWorkPackagesQuery",
    "PagedWorkPackageSummaryResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.detail",
    "workItems",
    "GET",
    "/api/v1/work-items/{workItemId}",
    "/work-packages/{workItemId}",
    "CanRead",
    "Work item ID",
    "WorkPackageDetailResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.comments.create",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/comments",
    "/work-packages/{workItemId}/comments",
    "CanWrite",
    "CreateWorkPackageCommentRequest",
    "WorkPackageCommentResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.comments.update.put",
    "workItems",
    "PUT",
    "/api/v1/work-items/{workItemId}/comments/{commentId}",
    "/work-packages/{workItemId}/comments/{commentId}",
    "CanWrite",
    "UpdateWorkPackageCommentRequest",
    "WorkPackageCommentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.comments.update.patch",
    "workItems",
    "PATCH",
    "/api/v1/work-items/{workItemId}/comments/{commentId}",
    "/work-packages/{workItemId}/comments/{commentId}",
    "CanWrite",
    "UpdateWorkPackageCommentRequest",
    "WorkPackageCommentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.comments.delete",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}/comments/{commentId}",
    "/work-packages/{workItemId}/comments/{commentId}",
    "CanWrite",
    "Path IDs",
    "WorkPackageCommentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.relations.add",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/relations",
    "/work-packages/{workItemId}/relations",
    "CanWriteProject",
    "AddWorkPackageRelationRequest",
    "WorkPackageRelationResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.relations.remove",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}/relations/{relationId}",
    "/work-packages/{workItemId}/relations/{relationId}",
    "CanWriteProject",
    "Path IDs",
    "WorkPackageRelationResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.watchers.add",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/watchers",
    "/work-packages/{workItemId}/watchers",
    "CanWrite",
    "AddWorkPackageWatcherRequest",
    "WorkPackageWatcherResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.watchers.remove",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}/watchers/{userId}",
    "/work-packages/{workItemId}/watchers/{userId}",
    "CanWrite",
    "Path IDs",
    "WorkPackageWatcherResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.attachments.add",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/attachments",
    "/work-packages/{workItemId}/attachments",
    "CanWrite",
    "AddWorkPackageAttachmentRequest",
    "WorkPackageAttachmentResponse",
    "specialized",
    "live-ui",
  ],
  [
    "work-items.attachments.upload-url",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/attachments/upload-url",
    "/work-packages/{workItemId}/attachments/upload-url",
    "CanWrite",
    "CreateWorkPackageAttachmentUploadUrlRequest",
    "WorkPackageAttachmentUploadUrlResponse",
    "passthrough",
    "ui-not-integrated",
    "The current attachment UI links metadata and does not upload a binary.",
  ],
  [
    "work-items.attachments.remove",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}/attachments/{attachmentId}",
    "/work-packages/{workItemId}/attachments/{attachmentId}",
    "CanWrite",
    "Path IDs",
    "WorkPackageAttachmentResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.labels.add",
    "workItems",
    "POST",
    "/api/v1/work-items/{workItemId}/labels",
    "/work-packages/{workItemId}/labels",
    "CanWrite",
    "AddLabelRequest",
    "LabelResponse",
    "passthrough",
    "no-ui",
  ],
  [
    "work-items.labels.remove",
    "workItems",
    "DELETE",
    "/api/v1/work-items/{workItemId}/labels/{labelId}",
    "/work-packages/{workItemId}/labels/{labelId}",
    "CanWrite",
    "Path IDs",
    "LabelResponse",
    "passthrough",
    "no-ui",
  ],
] as const satisfies readonly ContractTuple[];

export type BackendApiContractId = (typeof contractTuples)[number][0];
export type BackendApiContractIdForDomain<Domain extends BackendApiDomain> = Extract<
  (typeof contractTuples)[number],
  readonly [string, Domain, ...unknown[]]
>[0];

export const backendApiContracts: readonly BackendApiContract[] = contractTuples.map(
  ([
    id,
    domain,
    method,
    frontendPath,
    backendPath,
    policy,
    request,
    response,
    transport,
    ui,
    notes,
  ]) => ({
    backendPath,
    domain,
    frontendPath,
    id,
    method,
    ...(notes ? { notes } : {}),
    policy,
    request,
    response,
    transport,
    ui,
  }),
);
